apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 1m
  targetNamespace: monitoring
  install:
    createNamespace: true
  chart:
    spec:
      chart: grafana/promtail
      version: "5.2.2"
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: flux-system
  values:
    config:
      clients:
        - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
