apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  targetNamespace: monitoring
  install:
    createNamespace: true
  chart:
    spec:
      chart: grafana/loki
      version: "2.10.0"
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: flux-system
  values:
    persistence:
      enabled: false
    service:
      type: ClusterIP
