apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1m
  targetNamespace: monitoring
  install:
    createNamespace: true
  chart:
    spec:
      chart: grafana
      version: "6.22.3"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
    ingress:
      enabled: false
    adminUser: admin
    adminPassword: admin
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
