apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: wordpress
spec:
  interval: 1m
  targetNamespace: wordpress
  install:
    createNamespace: true
  chart:
    spec:
      chart: mysql
      version: "8.10.9"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    primary:
      persistence:
        enabled: false
    auth:
      existingSecret: mysql-credentials
