apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-resources
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/kube-practice"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-gitops
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
