apiVersion: v1
data:
  age.agekey: IyBjcmVhdGVkOiAyMDI1LTA5LTEzVDEyOjAxOjMyWgojIHB1YmxpYyBrZXk6IGFnZTEwOG45Y3dnZjVlYzB3bTZwbG1ldGZ1Y242dTBtMGVlNTZlN2NzbTN6aHFsZjZ0MHl6ZHFxZjBmbDIwCkFHRS1TRUNSRVQtS0VZLTFaNzdHNDdIV0U3TjlaTFlHUFI3R0dQUTVVNTg4V0g0TlRFUVA5R0daRVJGSE5NVkhYRzBRMko1M0QzCg==
kind: Secret
metadata:
  #creationTimestamp: "2025-09-13T12:17:45Z"
  name: sops-age
  namespace: flux-system
    #resourceVersion: "2626"
    #uid: 62296672-df0a-45fc-ab41-428044bdbb4c
type: Opaque
